---
all:
  hosts:
    ubuntu26-test:
      ansible_host: ubuntu26-test
      image: "docker.io/library/ubuntu:26.04"
    debian13-test:
      ansible_host: debian13-test
      image: "docker.io/library/debian:13"

  vars:
    # forces Molecule tasks (like converge) to communicate over Podman
    ansible_connection: containers.podman.podman
    ansible_user: root
    # ansible_remote_tmp: /tmp/ansible