# SPDX-License-Identifier: MIT-0
---
- name: APT configuration
  ansible.builtin.copy:
    src: "{{ item.key }}"
    dest: "/etc/apt/apt.conf.d/99{{ item.value }}"
    owner: root
    group: root
    mode: '0644'
  loop:
    - { key: 'apt_config', value: 'apt' }
    - { key: 'aptitude_config', value: 'aptitude' }


- name: Remove Docker APT language configuration
  ansible.builtin.file:
    path: /etc/apt/apt.conf.d/docker-no-languages
    state: absent
  when: ansible_facts['virtualization_type'] in ['docker', 'podman', 'containerd']

# - name: In a container - disable locale excludes - TODO or enable en_US only
#   ansible.builtin.lineinfile:
#     path: /etc/dpkg/dpkg.cfg.d/excludes
#     regexp: '^(path-exclude=/usr/share/locale/\*/LC_MESSAGES/\*\.mo)'
#     line: '#\1'
#     backrefs: true
#   register: base_config_dpkg_excludes_changed

- name: Update and upgrade packages
  ansible.builtin.apt:
    update_cache: true
    upgrade: "full"

- name: Mark automatically installed packages as such
  block:
    - name: Find manual packages that are required by others
      ansible.builtin.shell: |
        set -o pipefail
        comm -12 <(apt-mark showmanual | sort) \
                 <(apt-cache depends --no-conflicts --no-suggests $(dpkg-query -f '${Package}\n' -W) | awk '/Depends:/ {print $2}' | sort -u)
      register: base_config_packages_to_auto
      changed_when: false
      failed_when: false

    - name: Switch all found packages to auto
      ansible.builtin.command: "apt-mark auto {{ item }}"
      loop: "{{ base_config_packages_to_auto.stdout_lines }}"
      when: base_config_packages_to_auto.stdout_lines | length > 0
      register: base_config_apt_mark_result
      # Idempotence
      changed_when: "'marked as auto installed' in base_config_apt_mark_result.stdout"

- name: Install base packages
  ansible.builtin.apt:
    name: "{{ base_config_packages }}"
    state: present

- name: Disable etckeeper's auto-commit
  ansible.builtin.lineinfile:
    path: /etc/etckeeper/etckeeper.conf
    regexp: '^#?\s*{{ item.key }}='
    line: '{{ item.key }}={{ item.value }}'
    state: present
  loop:
    - { key: 'AVOID_DAILY_AUTOCOMMITS', value: '1' }
    - { key: 'AVOID_COMMIT_BEFORE_INSTALL', value: '1' }

- name: Set timezone
  community.general.timezone:
    name: "{{ base_config_system_timezone }}"

- name: Set locale
  block:
    - name: Locales to be generated
      ansible.builtin.debconf:
        name: locales
        question: locales/locales_to_be_generated
        value: "{{ base_config_locales | join(', ') }}"
        vtype: multiselect
      register: base_config_locales_generated

    - name: Set default locale
      ansible.builtin.debconf:
        name: locales
        question: locales/default_environment_locale
        value: en_US.UTF-8
        vtype: select
      register: base_config_lang_selected

    - name: Update locale system config
      ansible.builtin.command: dpkg-reconfigure --frontend=noninteractive locales
      when: base_config_locales_generated.changed or base_config_lang_selected.changed
      changed_when: true

- name: Bash configuration
  ansible.builtin.blockinfile:
    path: /etc/bash.bashrc
    insertafter: EOF
    marker: "# {mark} ANSIBLE MANAGED BASH CONFIG"
    block: "{{ lookup('ansible.builtin.file', 'bash_config') }}"

- name: Bash check window size
  ansible.builtin.lineinfile:
    path: /etc/bash.bashrc
    line: 'shopt -s checkwinsize'
    state: present
    create: false

- name: Enable Bash completion
  ansible.builtin.replace:
    path: /etc/bash.bashrc
    regexp: |
      (?m)^# (enable bash completion in interactive shells)\n#(if.*)\n#(.*)\n#(.*bash_completion)\n#(.*)\n#(.*)\n#(.*)\n#(fi)
    replace: |
      # \1
      \2
      \3
      \4
      \5
      \6
      \7
      \8

- name: Bash aliases
  ansible.builtin.blockinfile:
    path: /etc/bash.bashrc
    insertafter: EOF
    marker: "# {mark} ANSIBLE MANAGED BASH ALIASES"
    block: "{{ lookup('ansible.builtin.file', 'bash_aliases') }}"

- name: Htop configuration
  ansible.builtin.copy:
    src: htop_config
    dest: /etc/htoprc
    mode: "0644"

- name: Git configuration
  community.general.git_config:
    name: "alias.{{ item.key }}"
    value: "{{ item.value }}"
    scope: system
  loop:
    - { key: 's', value: 'status' }
    - { key: 'sa', value: 'status --ignored' }
    - { key: 'd', value: 'diff' }
    - { key: 'ds', value: 'diff --staged' }
    - { key: 'p', value: 'pull --recurse-submodules' }
    - { key: 'l', value: "log --graph -m --pretty='tformat:%h %C(auto) %ad %an %d %s' --date=short" }
    - { key: 'la', value: "log --graph -m --pretty='tformat:%h %C(auto) %ad %an %d %s' --date=short --all" }
    - { key: 'll', value: 'log --graph -m --stat --decorate --no-merges' }
    - { key: 'lla', value: 'log --graph -m --stat --decorate --no-merges --all' }
