---

- name: Create Podman test containers
  hosts: localhost
  connection: local
  gather_facts: false

  # no_log: "{{ molecule_no_log }}"

  tasks:
    - name: Spin up test instances
      containers.podman.podman_container:
        name: "{{ item }}"
        image: "{{ hostvars[item]['image'] }}"
        state: started
        # init: true    # requires catatonit in the devcontainer
        stop_timeout: 1 # don't wait too long before killing the container
        network: "pasta"
        auto_remove: false
        # tty: true
        command: sleep infinity
      # Loop through all inventory hosts (excluding localhost itself)
      loop: "{{ groups['all'] | reject('equalto', 'localhost') | list }}"

    - name: Install python for gather_facts
      containers.podman.podman_container_exec:
        name: "{{ item }}"
        command: "bash -c 'apt-get -o Acquire::ForceIPv4=true update && apt-get -o Acquire::ForceIPv4=true install -y python3'"
      loop: "{{ groups['all'] | reject('equalto', 'localhost') | list }}"
